### PR TITLE
Add check-features command

### PR DESCRIPTION
**Pull request by koenw**
The `check-features` subcommand checks all `Cargo.toml` files in a given folder for dependencies that have `default-features = false` but are not part of the `std` feature.

This functionality was originally requested in [Opstooling #55](https://github.com/paritytech/opstooling/issues/55) and further discussed in [Substrate #11715](https://github.com/paritytech/substrate/pull/11715).

In order to facilitate these changes I've also updated the `cargo_edit` dependency.

### CODE REVIEW

**Comment by ggwpez** [comment]
Is there a reason for parsing `Cargo.toml` files instead of using `cargo metadata`? It outputs JSON:
```
"dependencies": [
{
  "name": "lazy_static",
  …
  "optional": true,
  "uses_default_features": true,
  "features": [],
  …
},
…
```
and then whether or not it is enabled in the features:  
```
"features": {
  "default": [
    "heavyweight"
  ]
```

**Comment by koenw** [comment]
I guess that would work too, but I'm not working on this anymore so I haven't really thought about it.

**Comment by chevdor** [comment]
@koenw do you plan on keeping your work on this PR or shall we close it ?

**Comment by koenw** [comment]
@chevdor I do not plan to work on this PR, feel free to close.

**Pull request closed without merging**
